use_frameworks!

platform :ios, '8.0'

target 'CommixtureTransitionVC_Example' do
  pod 'CommixtureTransitionVC', :path => '../'

  target 'CommixtureTransitionVC_Tests' do
    inherit! :search_paths

    
  end
end
